### ISSUE TITLE
Error importing cartopy on Discover

### ISSUE THREAD

**Issue by danholdaway** [JCSDA/spack-stack#299]
**Describe the bug**

I have a problem importing cartopy on Discover. It seems to report not finding the geos python package, which must be a dependency of cartopy that wasn't installed. 

**To Reproduce**

On Discover (haven't tried other platforms):

```
module purge
module use /discover/swdev/jcsda/spack-stack/modulefiles
module load miniconda/3.9.7
module load ecflow/5.8.4
module use /discover/swdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/modulefiles/Core
module load stack-gcc/10.1.0
module load stack-openmpi/4.1.3
module load stack-python/3.9.7
module load jedi-ewok-env/1.0.0

python

import cartopy
```

**Expected behavior**
Clean import

**System:**
Discover

**Additional context**

```
>>> import cartopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-cartopy-0.20.2-cikufzu/lib/python3.9/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-cartopy-0.20.2-cikufzu/lib/python3.9/site-packages/cartopy/crs.py", line 22, in <module>
    import shapely.geometry as sgeom
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-shapely-1.8.0-5ij53hs/lib/python3.9/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-shapely-1.8.0-5ij53hs/lib/python3.9/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-shapely-1.8.0-5ij53hs/lib/python3.9/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-shapely-1.8.0-5ij53hs/lib/python3.9/site-packages/shapely/geos.py", line 93, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/discover/swdev/jcsda/spack-stack/miniconda-3.9.7/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /discover/swdev/jcsda/spack-stack/miniconda-3.9.7/lib/libgeos_c.so: cannot open shared object file: No such file or directory
```

**Comment by climbfuji** [comment]
Wondering why it is trying get libgeos from miniconda. Definitely didn't install it there.

**Comment by climbfuji** [comment]
I had this problem in the past (and I thought I had a fix for it ... now I just need to remember). It trips over some hacky logic in py-shapely:
```
    elif exists_conda_env():
        # conda package.
        _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
```
Because the Python interpreter is coming from miniconda, it thinks it is in a conda env and then tries to find it in that env (and since there is no conda env, it goes to the miniconda root dir).

**Comment by climbfuji** [comment]
We need to patch one of the shapely files when building py-shapely with spack-stack:
```
diff /gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-shapely-1.8.0-5ij53hs/lib/python3.9/site-packages/shapely/geos.py.backup.dom /gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/gcc/10.1.0/py-shapely-1.8.0-5ij53hs/lib/python3.9/site-packages/shapely/geos.py
91,93c91,93
<     elif exists_conda_env():
<         # conda package.
<         _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
---
>     #elif exists_conda_env():
>     #    # conda package.
>     #    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
```
I've made this change locally for GNU on Discover and it works. Will do the same for Intel (locally), but we'll need to create a patch in the spack-package (in our spack fork). Let's keep this issue open until we've got the patch in place.

**Comment by climbfuji** [comment]
I've patched all four installs manually (skylab-1.0.0 w/ intel and gnu, also 1.0.2 w/ intel and gnu) on Discover.

**Comment by danholdaway** [comment]
Thanks for the quick repair @climbfuji. Working for me now.

**Comment by climbfuji** [comment]
Reopening, because I only fixed it locally (manually) on Discover. PR with proper fix is https://github.com/NOAA-EMC/spack-stack/pull/300.

**Comment by climbfuji** [comment]
I also fixed this manually on Orion for both Intel and GNU.
