### ISSUE TITLE
Bug in release/1.3.0: py-h5py@3.6.0 incompatible with hdf5@1.14.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#513]
**Describe the bug**
See https://forum.hdfgroup.org/t/runtimeerror-wrong-file-driver-version/10123. PR https://github.com/h5py/h5py/pull/2187 fixed it for `py-h5py@3.8.0` 
```
module purge
module use /work/noaa/da/role-da/spack-stack/modulefiles
module load miniconda/3.9.7
module load ecflow/5.8.4
module load mysql/8.0.31
module use /work2/noaa/da/role-da/spack-stack-feature-r2d2-mysql/envs/unified-4.0.0-rc1/install/modulefiles/Core
module load stack-intel/2022.0.2
module load stack-intel-oneapi-mpi/2021.5.1
module load stack-python/3.9.7
module load py-h5py/3.6.0
module li

Currently Loaded Modules:
  1) ecflow/5.8.4     4) stack-intel/2022.0.2              7) miniconda/3.9.7     10) zlib/1.2.13      13) openblas/0.3.19       16) py-h5py/3.6.0
  2) mysql/8.0.31     5) impi/2022.1.2                     8) stack-python/3.9.7  11) hdf5/1.14.0      14) py-setuptools/59.4.0
  3) intel/2022.1.2   6) stack-intel-oneapi-mpi/2021.5.1   9) pkg-config/0.27.1   12) py-mpi4py/3.1.4  15) py-numpy/1.22.3

Orion-login-3[22] dheinzel$ python3
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work2/noaa/da/role-da/spack-stack-feature-r2d2-mysql/envs/unified-4.0.0-rc1/install/intel/2022.0.2/py-h5py-3.6.0-6om6r3h/lib/python3.9/site-packages/h5py/__init__.py", line 56, in <module>
    from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
  File "h5py/h5fd.pyx", line 219, in init h5py.h5fd
RuntimeError: Wrong file driver version # (wrong file driver version #)
>>>
```
**To Reproduce**
See above.

**Expected behavior**
It works!

**System:**
Any

**Additional context**
n/a

**Comment by climbfuji** [comment]
After installing `py-h5py@3.8.0`:
```
Orion-login-4[16] dheinzel$ module load py-h5py/3.8.0
Orion-login-4[17] dheinzel$ python3
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>>
```

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/514
