### ISSUE TITLE
Bug:  error report with Intel and spack stack v1.3.1 (on Orion) trying to run simobs/skylab_monitor.py

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA/spack-stack#565]
**Describe the bug**

When trying to run: `simobs/src/simobs/plotting/skylab_monitoring.py` I am getting an error about `scipy`.

**To Reproduce**

```
module purge
module use /work/noaa/da/role-da/spack-stack/modulefiles
module load miniconda/3.9.7
module load ecflow/5.8.4
module load mysql/8.0.31

module use /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/install/modulefiles/Core
module load stack-intel/2022.0.2
module load stack-intel-oneapi-mpi/2021.5.1
module load stack-python/3.9.7

module load jedi-fv3-env/unified-dev
module load jedi-ewok-env/unified-dev
module load soca-env/unified-dev

# !!! hack while ufo is not compatible with 2.4.1 !!!
module swap crtm/v2.4.1-jedi crtm/v2.4-jedi.2
# !!! hack while ufo is not compatible with 2.4.1 !!!

```

then from a JEDI_BUILD area, I followed readthedocs doing `python3 -m pip install -e .` and `source venv/bin/activate`

but running the plot script fails with:

```
Traceback (most recent call last):
  File "/work2/noaa/fv3-cam/gthompsn/src/fv3-bundle/simobs/src/simobs/plotting/skylab_monitor.py", line 24, in <module>
    from plot_profiles import \
  File "/work2/noaa/fv3-cam/gthompsn/src/fv3-bundle/simobs/src/simobs/plotting/plot_profiles.py", line 9, in <module>
    import scipy.stats as st
  File "/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/install/intel/2022.0.2/py-scipy-1.9.3-edtwns4/lib/python3.9/site-packages/scipy/stats/__init__.py", line 467, in <module>
    from ._stats_py import *
  File "/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/install/intel/2022.0.2/py-scipy-1.9.3-edtwns4/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 53, in <module>
    from ._hypotests import _all_partitions
  File "/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/install/intel/2022.0.2/py-scipy-1.9.3-edtwns4/lib/python3.9/site-packages/scipy/stats/_hypotests.py", line 13, in <module>
    from ._hypotests_pythran import _a_ij_Aij_Dij2
```

**Expected behavior**
Plotting should happen with PNG files output.

**System:**
Orion

**Comment by climbfuji** [comment]
@gthompsnJCSDA Thanks for submitting this bug report. I was able to reproduce this by loading the spack-stack meta modules (compiler, MPI, python), then loading py-scipy and then
```
python3 -c "import scipy.stats as st"
```
The reason is that for Intel, we build scipy without Pythran support. scipy in this case should either exit gracefully saying that scipy was built w/o Pythran support, or load the non-pythran version (which would be slower). I believe the latter was the intention, so that's a bug.

The reason we don't build scipy with pythran for Intel is that we had issues building pythran with Intel in the past. We can revisit that and in case it now works build scipy with Pythran support for Intel, too. I'll let you know.
