### ISSUE TITLE
Bug with py-numpy on Hercules

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#682]
**Describe the bug**
Building jedi-bundle with current spack-stack (as of 2023/07/20) on Hercules, seeing ctest failures for IODA python. The following tests failed. Something seems to be wrong with py-numpy.

Note that this issue is part of (and in parts a duplicate of) epic https://github.com/JCSDA-internal/skylab/issues/54.
```
        851 - ioda-obsspace-python (Failed)
        889 - test_ioda-engines-05-Py (Failed)
        890 - test_ioda-engines-06-Py (Failed)
        891 - test_ioda-engines-07a-Py-ObsSpaceClass (Failed)
        892 - test_ioda-engines-07b-Py-ObsSpaceClassDataTypes (Failed)
        893 - test_ioda-engines-chrono-Py (Failed)
        1540 - test_femps_csgrid (Failed)
        1692 - test_soca_forecast_pseudo (Failed)
        1719 - test_soca_hofx_4d_pseudo (Failed)
        1726 - test_soca_3dvarfgat_pseudo (Failed)
```
        From `test -R ioda-obsspace-python --verbose`:
```851: Test timeout computed to be: 1500
851: Traceback (most recent call last):
851:   File "/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/py-numpy-1.22.3-jksc5m5/lib64/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
851:     from . import multiarray
851:   File "/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/py-numpy-1.22.3-jksc5m5/lib64/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
851:     from . import overrides
851:   File "/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/py-numpy-1.22.3-jksc5m5/lib64/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
851:     from numpy.core._multiarray_umath import (
851: ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
851:
851: During handling of the above exception, another exception occurred:
851:
851: Traceback (most recent call last):
851:   File "/work2/noaa/da/dheinzel-new/skylab-test-20230717-hercules/jedi-bundle/ioda/src/engines/test/ioda/python/test_ioda_obsspace.py", line 3, in <module>
851:     import numpy as np
851:   File "/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/py-numpy-1.22.3-jksc5m5/lib64/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
851:     from . import core
851:   File "/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/intel/2021.9.0/py-numpy-1.22.3-jksc5m5/lib64/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
851:     raise ImportError(msg)
851: ImportError:
851:
851: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
851:
851: Importing the numpy C-extensions failed. This error can happen for
851: many reasons, often due to issues with your setup or how NumPy was
851: installed.
851:
851: We have compiled some common reasons and troubleshooting tips at:
851:
851:     https://numpy.org/devdocs/user/troubleshooting-importerror.html
851:
851: Please note and check the following:
851:
851:   * The Python version is: Python3.10 from "/apps/spack-managed/gcc-11.3.1/python-3.10.8-4kb4l6xa6dx4qnzyf5sctojg5vidplmo/bin/python3.10"
851:   * The NumPy version is: "1.22.3"
851:
851: and make sure that they are the versions you expect.
851: Please carefully study the documentation linked above for further help.
851:
851: Original error was: No module named 'numpy.core._multiarray_umath'
851:
1/1 Test #851: ioda-obsspace-python .............***Failed    0.41 sec
```

**To Reproduce**
See above

**Expected behavior**
It works

**System:**
Hercules, `/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/` with Intel

**Additional context**
n/a

**Comment by climbfuji** [comment]
This is fixed with #720
